/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as StoreRouteImport } from './routes/store'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as BoxersIndexRouteImport } from './routes/boxers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as BoxersUsernameRouteImport } from './routes/boxers.$username'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFightersRouteImport } from './routes/admin.fighters'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth.discord.callback'
import { Route as AdminVideosNewRouteImport } from './routes/admin.videos.new'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminFightersNewRouteImport } from './routes/admin.fighters.new'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminVideosIdEditRouteImport } from './routes/admin.videos.$id.edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin.products.$id.edit'
import { Route as AdminFightersUsernameEditRouteImport } from './routes/admin.fighters.$username.edit'
import { Route as AdminEventsSlugEditRouteImport } from './routes/admin.events.$slug.edit'
import { Route as AdminArticlesSlugEditRouteImport } from './routes/admin.articles.$slug.edit'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxersIndexRoute = BoxersIndexRouteImport.update({
  id: '/boxers/',
  path: '/boxers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxersUsernameRoute = BoxersUsernameRouteImport.update({
  id: '/boxers/$username',
  path: '/boxers/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFightersRoute = AdminFightersRouteImport.update({
  id: '/fighters',
  path: '/fighters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/auth/discord/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosNewRoute = AdminVideosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminVideosRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminFightersNewRoute = AdminFightersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminFightersRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const AdminVideosIdEditRoute = AdminVideosIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminVideosRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminFightersUsernameEditRoute =
  AdminFightersUsernameEditRouteImport.update({
    id: '/$username/edit',
    path: '/$username/edit',
    getParentRoute: () => AdminFightersRoute,
  } as any)
const AdminEventsSlugEditRoute = AdminEventsSlugEditRouteImport.update({
  id: '/$slug/edit',
  path: '/$slug/edit',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminArticlesSlugEditRoute = AdminArticlesSlugEditRouteImport.update({
  id: '/$slug/edit',
  path: '/$slug/edit',
  getParentRoute: () => AdminArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/champions': typeof ChampionsRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/rankings': typeof RankingsRoute
  '/store': typeof StoreRoute
  '/videos': typeof VideosRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/fighters': typeof AdminFightersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/boxers/$username': typeof BoxersUsernameRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/boxers/': typeof BoxersIndexRoute
  '/news/': typeof NewsIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/fighters/new': typeof AdminFightersNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/admin/articles/$slug/edit': typeof AdminArticlesSlugEditRoute
  '/admin/events/$slug/edit': typeof AdminEventsSlugEditRoute
  '/admin/fighters/$username/edit': typeof AdminFightersUsernameEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/videos/$id/edit': typeof AdminVideosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/rankings': typeof RankingsRoute
  '/store': typeof StoreRoute
  '/videos': typeof VideosRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/fighters': typeof AdminFightersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/boxers/$username': typeof BoxersUsernameRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/boxers': typeof BoxersIndexRoute
  '/news': typeof NewsIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/fighters/new': typeof AdminFightersNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/admin/articles/$slug/edit': typeof AdminArticlesSlugEditRoute
  '/admin/events/$slug/edit': typeof AdminEventsSlugEditRoute
  '/admin/fighters/$username/edit': typeof AdminFightersUsernameEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/videos/$id/edit': typeof AdminVideosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/champions': typeof ChampionsRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/rankings': typeof RankingsRoute
  '/store': typeof StoreRoute
  '/videos': typeof VideosRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/fighters': typeof AdminFightersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/boxers/$username': typeof BoxersUsernameRoute
  '/news/$slug': typeof NewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/boxers/': typeof BoxersIndexRoute
  '/news/': typeof NewsIndexRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/fighters/new': typeof AdminFightersNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/admin/articles/$slug/edit': typeof AdminArticlesSlugEditRoute
  '/admin/events/$slug/edit': typeof AdminEventsSlugEditRoute
  '/admin/fighters/$username/edit': typeof AdminFightersUsernameEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/videos/$id/edit': typeof AdminVideosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/champions'
    | '/events'
    | '/feed'
    | '/rankings'
    | '/store'
    | '/videos'
    | '/admin/articles'
    | '/admin/events'
    | '/admin/fighters'
    | '/admin/login'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/videos'
    | '/auth/login'
    | '/boxers/$username'
    | '/news/$slug'
    | '/admin/'
    | '/boxers/'
    | '/news/'
    | '/admin/articles/new'
    | '/admin/events/new'
    | '/admin/fighters/new'
    | '/admin/posts/new'
    | '/admin/products/new'
    | '/admin/videos/new'
    | '/auth/discord/callback'
    | '/admin/articles/$slug/edit'
    | '/admin/events/$slug/edit'
    | '/admin/fighters/$username/edit'
    | '/admin/products/$id/edit'
    | '/admin/videos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/champions'
    | '/events'
    | '/feed'
    | '/rankings'
    | '/store'
    | '/videos'
    | '/admin/articles'
    | '/admin/events'
    | '/admin/fighters'
    | '/admin/login'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/videos'
    | '/auth/login'
    | '/boxers/$username'
    | '/news/$slug'
    | '/admin'
    | '/boxers'
    | '/news'
    | '/admin/articles/new'
    | '/admin/events/new'
    | '/admin/fighters/new'
    | '/admin/posts/new'
    | '/admin/products/new'
    | '/admin/videos/new'
    | '/auth/discord/callback'
    | '/admin/articles/$slug/edit'
    | '/admin/events/$slug/edit'
    | '/admin/fighters/$username/edit'
    | '/admin/products/$id/edit'
    | '/admin/videos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/champions'
    | '/events'
    | '/feed'
    | '/rankings'
    | '/store'
    | '/videos'
    | '/admin/articles'
    | '/admin/events'
    | '/admin/fighters'
    | '/admin/login'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/videos'
    | '/auth/login'
    | '/boxers/$username'
    | '/news/$slug'
    | '/admin/'
    | '/boxers/'
    | '/news/'
    | '/admin/articles/new'
    | '/admin/events/new'
    | '/admin/fighters/new'
    | '/admin/posts/new'
    | '/admin/products/new'
    | '/admin/videos/new'
    | '/auth/discord/callback'
    | '/admin/articles/$slug/edit'
    | '/admin/events/$slug/edit'
    | '/admin/fighters/$username/edit'
    | '/admin/products/$id/edit'
    | '/admin/videos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChampionsRoute: typeof ChampionsRoute
  EventsRoute: typeof EventsRoute
  FeedRoute: typeof FeedRoute
  RankingsRoute: typeof RankingsRoute
  StoreRoute: typeof StoreRoute
  VideosRoute: typeof VideosRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BoxersUsernameRoute: typeof BoxersUsernameRoute
  NewsSlugRoute: typeof NewsSlugRoute
  BoxersIndexRoute: typeof BoxersIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxers/': {
      id: '/boxers/'
      path: '/boxers'
      fullPath: '/boxers/'
      preLoaderRoute: typeof BoxersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxers/$username': {
      id: '/boxers/$username'
      path: '/boxers/$username'
      fullPath: '/boxers/$username'
      preLoaderRoute: typeof BoxersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fighters': {
      id: '/admin/fighters'
      path: '/fighters'
      fullPath: '/admin/fighters'
      preLoaderRoute: typeof AdminFightersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos/new': {
      id: '/admin/videos/new'
      path: '/new'
      fullPath: '/admin/videos/new'
      preLoaderRoute: typeof AdminVideosNewRouteImport
      parentRoute: typeof AdminVideosRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/fighters/new': {
      id: '/admin/fighters/new'
      path: '/new'
      fullPath: '/admin/fighters/new'
      preLoaderRoute: typeof AdminFightersNewRouteImport
      parentRoute: typeof AdminFightersRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/admin/videos/$id/edit': {
      id: '/admin/videos/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/videos/$id/edit'
      preLoaderRoute: typeof AdminVideosIdEditRouteImport
      parentRoute: typeof AdminVideosRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/fighters/$username/edit': {
      id: '/admin/fighters/$username/edit'
      path: '/$username/edit'
      fullPath: '/admin/fighters/$username/edit'
      preLoaderRoute: typeof AdminFightersUsernameEditRouteImport
      parentRoute: typeof AdminFightersRoute
    }
    '/admin/events/$slug/edit': {
      id: '/admin/events/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/admin/events/$slug/edit'
      preLoaderRoute: typeof AdminEventsSlugEditRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/articles/$slug/edit': {
      id: '/admin/articles/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/admin/articles/$slug/edit'
      preLoaderRoute: typeof AdminArticlesSlugEditRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
  }
}

interface AdminArticlesRouteChildren {
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesSlugEditRoute: typeof AdminArticlesSlugEditRoute
}

const AdminArticlesRouteChildren: AdminArticlesRouteChildren = {
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesSlugEditRoute: AdminArticlesSlugEditRoute,
}

const AdminArticlesRouteWithChildren = AdminArticlesRoute._addFileChildren(
  AdminArticlesRouteChildren,
)

interface AdminEventsRouteChildren {
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsSlugEditRoute: typeof AdminEventsSlugEditRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsSlugEditRoute: AdminEventsSlugEditRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminFightersRouteChildren {
  AdminFightersNewRoute: typeof AdminFightersNewRoute
  AdminFightersUsernameEditRoute: typeof AdminFightersUsernameEditRoute
}

const AdminFightersRouteChildren: AdminFightersRouteChildren = {
  AdminFightersNewRoute: AdminFightersNewRoute,
  AdminFightersUsernameEditRoute: AdminFightersUsernameEditRoute,
}

const AdminFightersRouteWithChildren = AdminFightersRoute._addFileChildren(
  AdminFightersRouteChildren,
)

interface AdminPostsRouteChildren {
  AdminPostsNewRoute: typeof AdminPostsNewRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsNewRoute: AdminPostsNewRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminVideosRouteChildren {
  AdminVideosNewRoute: typeof AdminVideosNewRoute
  AdminVideosIdEditRoute: typeof AdminVideosIdEditRoute
}

const AdminVideosRouteChildren: AdminVideosRouteChildren = {
  AdminVideosNewRoute: AdminVideosNewRoute,
  AdminVideosIdEditRoute: AdminVideosIdEditRoute,
}

const AdminVideosRouteWithChildren = AdminVideosRoute._addFileChildren(
  AdminVideosRouteChildren,
)

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRouteWithChildren
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminFightersRoute: typeof AdminFightersRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminVideosRoute: typeof AdminVideosRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRouteWithChildren,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminFightersRoute: AdminFightersRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminVideosRoute: AdminVideosRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChampionsRoute: ChampionsRoute,
  EventsRoute: EventsRoute,
  FeedRoute: FeedRoute,
  RankingsRoute: RankingsRoute,
  StoreRoute: StoreRoute,
  VideosRoute: VideosRoute,
  AuthLoginRoute: AuthLoginRoute,
  BoxersUsernameRoute: BoxersUsernameRoute,
  NewsSlugRoute: NewsSlugRoute,
  BoxersIndexRoute: BoxersIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
